/* Codex additive data layer. Source snapshot 2026-09-28; not live. */
window.NADIA_DATA_META = {
  "sourceAsOf": "2026-09-28",
  "live": false,
  "title": "Nadia’s 21-home wider list",
  "source": "Team Paley wider-list PDF, September 28, 2026",
  "sourcePDF": "wider-list-2026-09-28.pdf",
  "criteria": {
    "priceMin": 800000,
    "priceMax": 900000,
    "bedsMin": 3,
    "bathsMin": 2.5,
    "listedSqftMin": 2000,
    "acresMin": 0.14,
    "taxesMax": 18000
  },
  "disclaimer": "Private design preview using saved listing evidence. Prices, status and measurements are not live. Drive and rail figures are separate illustrative estimates, not door-to-door times.",
  "credit": "Listing data and photographs: OneKey® MLS and each named listing broker. Deemed reliable, not guaranteed."
};
window.NADIA_HOMES = [
  {
    "id": 1,
    "uid": "mls-1049913",
    "packetNumber": 1,
    "address": "9 Honeysuckle Lane",
    "town": "Kings Park",
    "price": 895000,
    "beds": 4,
    "baths": 3,
    "sqft": 2180,
    "acres": 0.23,
    "taxes": 12500,
    "dom": 11,
    "station": "Kings Park",
    "drive": "5 min",
    "rail": "80 min to Penn · sample rail trip",
    "railMinutes": 80,
    "kitchen": "Renovated top to bottom; updated kitchen with a center island, granite, open floor plan.",
    "fit": "Renovated island kitchen, three full baths and an in-ground pool.",
    "tradeoff": "Window/wall A/C. Basement and attic area are not separately documented.",
    "verification": "MLS lists 2,180 sq ft; finished basement and partly finished attic described, but no separate measured breakdown.",
    "broker": "Coldwell Banker American Homes",
    "mls": "1049913",
    "url": "https://portal.onehome.com/en-US/share/5531751I37286",
    "image": "assets/home-01.jpg",
    "photos": [
      "assets/home-01.jpg",
      "assets/home-01-photo-01.jpg",
      "assets/home-01-photo-02.jpg",
      "assets/home-01-photo-03.jpg",
      "assets/home-01-photo-04.jpg",
      "assets/home-01-photo-05.jpg"
    ],
    "isOriginal": true,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 3,
    "photoCredit": "OneKey® MLS · Coldwell Banker American Homes",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 2,
    "uid": "mls-1044068",
    "packetNumber": 2,
    "address": "14 Format Lane",
    "town": "Smithtown",
    "price": 850000,
    "beds": 4,
    "baths": 2.5,
    "sqft": 2500,
    "acres": 0.23,
    "taxes": 15295,
    "dom": 30,
    "station": "Smithtown",
    "drive": "7–12 min",
    "rail": "88 min to Penn · sample rail trip",
    "railMinutes": 88,
    "kitchen": "Fully updated kitchen with a center island, open to the dining and living rooms.",
    "fit": "Island kitchen, four bedrooms and an in-ground pool; listed at 2,500 sq ft.",
    "tradeoff": "Window/wall A/C; verify the listed square footage.",
    "verification": "MLS reports 2,500 sq ft; the measured breakdown by floor needs confirmation.",
    "broker": "Better Homes & Gardens Real Estate Realty Connect",
    "mls": "1044068",
    "url": "https://portal.onehome.com/en-US/share/5531774C33624",
    "image": "assets/home-02.jpg",
    "photos": [
      "assets/home-02.jpg",
      "assets/home-02-photo-01.jpg",
      "assets/home-02-photo-02.jpg",
      "assets/home-02-photo-03.jpg",
      "assets/home-02-photo-04.jpg",
      "assets/home-02-photo-05.jpg"
    ],
    "isOriginal": true,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 3,
    "photoCredit": "OneKey® MLS · Better Homes & Gardens Real Estate Realty Connect",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 3,
    "uid": "mls-1032254",
    "packetNumber": 3,
    "address": "7 Weinmann Boulevard",
    "town": "Melville",
    "price": 869000,
    "beds": 3,
    "baths": 3,
    "sqft": 2100,
    "acres": 0.32,
    "taxes": 11216,
    "dom": 60,
    "station": "Wyandanch",
    "drive": "6–8 min",
    "rail": "60 min to Penn · sample rail trip",
    "railMinutes": 60,
    "kitchen": "Brand-new kitchen: 9-foot center island, quartz/quartzite counters, stainless appliances, soaring ceilings.",
    "fit": "New island kitchen, three full baths and a finished walk-out level.",
    "tradeoff": "No garage; renovation condition needs confirmation.",
    "verification": "Listed at 2,100 sq ft; floor-area breakdown and renovation condition need confirmation.",
    "broker": "Property Professionals Realty",
    "mls": "1032254",
    "url": "https://portal.onehome.com/en-US/share/5531755D60066",
    "image": "assets/home-03.jpg",
    "photos": [
      "assets/home-03.jpg",
      "assets/home-03-photo-01.jpg",
      "assets/home-03-photo-02.jpg",
      "assets/home-03-photo-03.jpg",
      "assets/home-03-photo-04.jpg",
      "assets/home-03-photo-05.jpg"
    ],
    "isOriginal": true,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 4,
    "photoCredit": "OneKey® MLS · Property Professionals Realty",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 4,
    "uid": "mls-1052736",
    "packetNumber": 4,
    "address": "719 Glenridge Lane",
    "town": "East Northport",
    "price": 849000,
    "beds": 4,
    "baths": 2.5,
    "sqft": 2159,
    "acres": 0.25,
    "taxes": 12623,
    "dom": 4,
    "station": "Northport",
    "drive": "5 min",
    "rail": "72 min to Penn · sample rail trip",
    "railMinutes": 72,
    "kitchen": "Updated kitchen with granite counters; open floor plan; described as move-in ready.",
    "fit": "Updated kitchen, fenced yard and a short station drive.",
    "tradeoff": "Island not confirmed; lower-level area is not separately documented.",
    "verification": "MLS lists 2,159 sq ft. Lower-level area and freestanding island need confirmation.",
    "broker": "Better Homes & Gardens Real Estate Realty Connect",
    "mls": "1052736",
    "url": "https://portal.onehome.com/en-US/share/5531787D80943",
    "image": "assets/home-04.jpg",
    "photos": [
      "assets/home-04.jpg",
      "assets/home-04-photo-01.jpg",
      "assets/home-04-photo-02.jpg",
      "assets/home-04-photo-03.jpg",
      "assets/home-04-photo-04.jpg",
      "assets/home-04-photo-05.jpg"
    ],
    "isOriginal": true,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 4,
    "photoCredit": "OneKey® MLS · Better Homes & Gardens Real Estate Realty Connect",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 5,
    "uid": "mls-1041009",
    "packetNumber": 5,
    "address": "11 Penguin Lane",
    "town": "Commack",
    "price": 898000,
    "beds": 4,
    "baths": 3,
    "sqft": "MLS 2,500; plan 2,104",
    "acres": 0.35,
    "taxes": 13000,
    "dom": 38,
    "station": "Deer Park",
    "drive": "9–14 min",
    "rail": "65 min to Penn · sample rail trip",
    "railMinutes": 65,
    "kitchen": "Renovated kitchen with granite and stainless appliances. Freestanding-island configuration needs confirmation.",
    "fit": "Renovated kitchen, three full baths and a two-car garage.",
    "tradeoff": "Published floor plan and MLS square footage disagree; hi-ranch layout.",
    "verification": "MLS lists 2,500 sq ft; the published floor plan totals 2,104 (1,382 first floor + 722 lower level). Measurements and a freestanding kitchen island need confirmation.",
    "broker": "World Properties International Sea to Sky",
    "mls": "1041009",
    "url": "https://portal.onehome.com/en-US/share/5531747L04146",
    "image": "assets/home-05.jpg",
    "photos": [
      "assets/home-05.jpg",
      "assets/home-05-photo-01.jpg",
      "assets/home-05-photo-02.jpg",
      "assets/home-05-photo-03.jpg",
      "assets/home-05-photo-04.jpg",
      "assets/home-05-photo-05.jpg"
    ],
    "isOriginal": true,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 5,
    "photoCredit": "OneKey® MLS · World Properties International Sea to Sky",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 6,
    "uid": "mls-1051385",
    "packetNumber": 6,
    "address": "281 Town Line Road",
    "town": "East Northport",
    "price": 849000,
    "beds": 4,
    "baths": 3,
    "sqft": 3578,
    "acres": 0.46,
    "taxes": 14173,
    "dom": 11,
    "station": "Greenlawn",
    "drive": "12 min",
    "rail": "67 min to Penn · sample rail trip",
    "railMinutes": 67,
    "kitchen": "Updated eat-in kitchen: maple cabinetry, granite counters, stainless appliances; open to the dining room.",
    "fit": "Listed at 3,578 sq ft on .46 acre, with an in-ground pool.",
    "tradeoff": "Through road, no garage; freestanding island not confirmed.",
    "verification": "MLS reports 3,578 sq ft; the breakdown by floor needs confirmation. Kitchen photos show an attached counter; a freestanding island is not confirmed.",
    "broker": "Howard Hanna Coach",
    "mls": "1051385",
    "url": "https://portal.onehome.com/en-US/share/5531791m32092",
    "image": "assets/home-06.jpg",
    "photos": [
      "assets/home-06.jpg",
      "assets/home-06-photo-01.jpg",
      "assets/home-06-photo-02.jpg",
      "assets/home-06-photo-03.jpg",
      "assets/home-06-photo-04.jpg",
      "assets/home-06-photo-05.jpg"
    ],
    "isOriginal": true,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 5,
    "photoCredit": "OneKey® MLS · Howard Hanna Coach",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 7,
    "uid": "mls-1053132",
    "packetNumber": 7,
    "address": "29 Abbot Road",
    "town": "Smithtown",
    "price": 855000,
    "beds": 4,
    "baths": 2.5,
    "sqft": 2300,
    "acres": 0.25,
    "taxes": 14375,
    "dom": 7,
    "station": "Smithtown",
    "drive": "6–9 min",
    "rail": "88 min to Penn · sample rail trip",
    "railMinutes": 88,
    "kitchen": "Eat-in kitchen with maple cabinetry, granite counters and stainless appliances; updated bathrooms.",
    "fit": "Four bedrooms, granite kitchen and a two-car garage.",
    "tradeoff": "Kitchen renovation and island are not established; listed at 2,300 sq ft.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "Signature Premier Properties",
    "mls": "1053132",
    "url": "https://portal.onehome.com/en-US/share/5531758i67542",
    "image": "assets/home-07.jpg",
    "photos": [
      "assets/home-07.jpg",
      "assets/home-07-photo-01.jpg",
      "assets/home-07-photo-02.jpg",
      "assets/home-07-photo-03.jpg",
      "assets/home-07-photo-04.jpg",
      "assets/home-07-photo-05.jpg"
    ],
    "isOriginal": true,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 6,
    "photoCredit": "OneKey® MLS · Signature Premier Properties",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 8,
    "uid": "mls-1048941",
    "packetNumber": 8,
    "address": "17 White Cliff Lane",
    "town": "Nesconset",
    "price": 899000,
    "beds": 4,
    "baths": 2.5,
    "sqft": 2242,
    "acres": 0.25,
    "taxes": 15003,
    "dom": 15,
    "station": "St. James",
    "drive": "10 min",
    "rail": "93 min to Penn · sample rail trip",
    "railMinutes": 93,
    "kitchen": "Eat-in kitchen with granite counters and stainless appliances, open to a den with a wood-burning fireplace.",
    "fit": "Four bedrooms, in-ground pool and several recent exterior updates.",
    "tradeoff": "At the top of the budget; oil heat; island not confirmed.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "The Agency Northshore NY",
    "mls": "1048941",
    "url": "https://portal.onehome.com/en-US/share/5531743s92243",
    "image": "assets/home-08.jpg",
    "photos": [
      "assets/home-08.jpg",
      "assets/home-08-photo-01.jpg",
      "assets/home-08-photo-02.jpg",
      "assets/home-08-photo-03.jpg",
      "assets/home-08-photo-04.jpg",
      "assets/home-08-photo-05.jpg"
    ],
    "isOriginal": true,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 6,
    "photoCredit": "OneKey® MLS · The Agency Northshore NY",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 9,
    "uid": "mls-1041512",
    "packetNumber": 9,
    "address": "20 Howard Street",
    "town": "Hicksville",
    "price": 899000,
    "beds": 4,
    "baths": 3,
    "sqft": 2000,
    "acres": 0.14,
    "taxes": 11217,
    "dom": 37,
    "station": "Hicksville",
    "drive": "4–7 min",
    "rail": "47 min to Penn · sample rail trip",
    "railMinutes": 47,
    "kitchen": "Renovated chef's kitchen: quartz counters, custom white cabinetry, mosaic backsplash, stainless appliances and a large center island.",
    "fit": "Renovated island kitchen, four bedrooms and access to Hicksville station.",
    "tradeoff": "2,000 listed sq ft on .14 acre; oil heat and window A/C.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "JAGGI Real Estate",
    "mls": "1041512",
    "url": "https://portal.onehome.com/en-US/share/5534715f43703",
    "image": "assets/home-09.jpg",
    "photos": [
      "assets/home-09.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 7,
    "photoCredit": "OneKey® MLS · JAGGI Real Estate",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 10,
    "uid": "mls-1005114",
    "packetNumber": 10,
    "address": "38 Fireplace Lane",
    "town": "Hicksville",
    "price": 879000,
    "beds": 5,
    "baths": 3,
    "sqft": 2500,
    "acres": 0.18,
    "taxes": 12500,
    "dom": 121,
    "station": "Hicksville",
    "drive": "6–12 min",
    "rail": "47 min to Penn · sample rail trip",
    "railMinutes": 47,
    "kitchen": "Renovated kitchen with granite counters as part of a full rebuild — new roof, siding, flooring, baths, staircase; no island mentioned.",
    "fit": "Five bedrooms and 2,500 listed sq ft with a renovated kitchen.",
    "tradeoff": ".18-acre lot, carport rather than garage, no basement; island not confirmed.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "Douglas Elliman Real Estate",
    "mls": "1005114",
    "url": "https://portal.onehome.com/en-US/share/5534727n94880",
    "image": "assets/home-10.jpg",
    "photos": [
      "assets/home-10.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 7,
    "photoCredit": "OneKey® MLS · Douglas Elliman Real Estate",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 11,
    "uid": "mls-1035498",
    "packetNumber": 11,
    "address": "197 Stephen Street",
    "town": "Levittown",
    "price": 849999,
    "beds": 3,
    "baths": 2.5,
    "sqft": 2108,
    "acres": 0.16,
    "taxes": 12324,
    "dom": 31,
    "station": "Hicksville",
    "drive": "7–12 min",
    "rail": "47 min to Penn · sample rail trip",
    "railMinutes": 47,
    "kitchen": "Eat-in kitchen; not described as updated.",
    "fit": "A Levittown option with three bedrooms, finished basement and two-car garage.",
    "tradeoff": "Kitchen condition and island not established; window A/C.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "North Star Home Services",
    "mls": "1035498",
    "url": "https://portal.onehome.com/en-US/share/5534728M10346",
    "image": "assets/home-11.jpg",
    "photos": [
      "assets/home-11.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 8,
    "photoCredit": "OneKey® MLS · North Star Home Services",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 12,
    "uid": "mls-1039621",
    "packetNumber": 12,
    "address": "95 Colonial Drive",
    "town": "Massapequa",
    "price": 899988,
    "beds": 4,
    "baths": 2.5,
    "sqft": 2032,
    "acres": 0.15,
    "taxes": 12745,
    "dom": 41,
    "station": "Amityville",
    "drive": "5 min",
    "rail": "63 min to Penn · sample rail trip",
    "railMinutes": 63,
    "kitchen": "Renovated eat-in kitchen: custom cabinetry, quartz counters, stainless appliances, designer backsplash and an oversized peninsula (not an island).",
    "fit": "Renovated four-bedroom home with a new roof and quartz kitchen.",
    "tradeoff": "2,032 sq ft on .15 acre; kitchen has a peninsula, not an island.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "Signature Premier Properties",
    "mls": "1039621",
    "url": "https://portal.onehome.com/en-US/share/5534731u80419",
    "image": "assets/home-12.jpg",
    "photos": [
      "assets/home-12.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 8,
    "photoCredit": "OneKey® MLS · Signature Premier Properties",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 13,
    "uid": "mls-1049724",
    "packetNumber": 13,
    "address": "3 Rosewood Drive",
    "town": "Massapequa",
    "price": 849999,
    "beds": 4,
    "baths": 3,
    "sqft": 2600,
    "acres": 0.18,
    "taxes": 17607,
    "dom": 11,
    "station": "Massapequa",
    "drive": "5–8 min",
    "rail": "61 min to Penn · sample rail trip",
    "railMinutes": 61,
    "kitchen": "Eat-in kitchen; the listing does not describe it.",
    "fit": "Four bedrooms, three full baths and 2,600 listed sq ft in Massapequa.",
    "tradeoff": "Kitchen and condition need review; lot figures conflict; highest taxes in this set.",
    "verification": "Lot conflict: listing .18 acre versus 9,240 sq ft (about .212 acre). Kitchen and condition are not established.",
    "broker": "Exit Realty All Pro",
    "mls": "1049724",
    "url": "https://portal.onehome.com/en-US/share/5534733Q46378",
    "image": "assets/home-13.jpg",
    "photos": [
      "assets/home-13.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 9,
    "photoCredit": "OneKey® MLS · Exit Realty All Pro",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 14,
    "uid": "mls-1012878",
    "packetNumber": 14,
    "address": "384 Scudder Avenue, Lot 2",
    "town": "Copiague",
    "price": 869000,
    "beds": 4,
    "baths": 2.5,
    "sqft": 2328,
    "acres": 0.16,
    "taxes": 17000,
    "dom": 107,
    "station": "Copiague",
    "drive": "3 min",
    "rail": "65 min to Penn · sample rail trip",
    "railMinutes": 65,
    "kitchen": "New: eat-in kitchen with granite counters and a generous center island.",
    "fit": "New construction with four bedrooms, an island kitchen and central air.",
    "tradeoff": "Confirm new-build taxes and completion details; crawl space.",
    "verification": "New construction: $17,000 taxes are listing-reported; confirm final assessment and completion details.",
    "broker": "Above Board Real Estate",
    "mls": "1012878",
    "url": "https://portal.onehome.com/en-US/share/5534749J36278",
    "image": "assets/home-14.jpg",
    "photos": [
      "assets/home-14.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 9,
    "photoCredit": "OneKey® MLS · Above Board Real Estate",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 15,
    "uid": "mls-1037727",
    "packetNumber": 15,
    "address": "59 Southard Avenue",
    "town": "West Babylon",
    "price": 849000,
    "beds": 4,
    "baths": 3,
    "sqft": 2300,
    "acres": 0.16,
    "taxes": 15592,
    "dom": 30,
    "station": "Babylon",
    "drive": "5–7 min",
    "rail": "68 min to Penn · sample rail trip",
    "railMinutes": 68,
    "kitchen": "Kitchen with quartz counters, stainless appliances and a center island with seating.",
    "fit": "Built in 2018 with three full baths, an island kitchen and a finished basement.",
    "tradeoff": "2,300 listed sq ft on .16 acre; review the smaller lot.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "Service Realty",
    "mls": "1037727",
    "url": "https://portal.onehome.com/en-US/share/5534750z88785",
    "image": "assets/home-15.jpg",
    "photos": [
      "assets/home-15.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 10,
    "photoCredit": "OneKey® MLS · Service Realty",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 16,
    "uid": "mls-1053506",
    "packetNumber": 16,
    "address": "4 Larkspur Drive",
    "town": "West Islip",
    "price": 879900,
    "beds": 4,
    "baths": 2.5,
    "sqft": 2390,
    "acres": 0.25,
    "taxes": 16603,
    "dom": 2,
    "station": "Babylon",
    "drive": "6–8 min",
    "rail": "68 min to Penn · sample rail trip",
    "railMinutes": 68,
    "kitchen": "Not described in the listing.",
    "fit": "Four bedrooms on .25 acre, with an in-ground pool and koi pond.",
    "tradeoff": "Kitchen and updates are not described; no basement; oil heat.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "Howard Hanna Coach",
    "mls": "1053506",
    "url": "https://portal.onehome.com/en-US/share/5534757D69315",
    "image": "assets/home-16.jpg",
    "photos": [
      "assets/home-16.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 10,
    "photoCredit": "OneKey® MLS · Howard Hanna Coach",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 17,
    "uid": "mls-1049845",
    "packetNumber": 17,
    "address": "43 Horton Street",
    "town": "West Islip",
    "price": 824900,
    "beds": 5,
    "baths": 3.5,
    "sqft": 3200,
    "acres": 0.25,
    "taxes": 15978,
    "dom": 13,
    "station": "Bay Shore",
    "drive": "7–12 min",
    "rail": "70 min to Penn · sample rail trip",
    "railMinutes": 70,
    "kitchen": "Not described in the listing; stainless appliances.",
    "fit": "Five bedrooms and 3,200 listed sq ft, with an in-ground pool.",
    "tradeoff": "Listing invites a project; no garage, no basement and cesspool.",
    "verification": "The listing suggests work may be needed; condition needs confirmation.",
    "broker": "Signature Premier Properties",
    "mls": "1049845",
    "url": "https://portal.onehome.com/en-US/share/5534759J41315",
    "image": "assets/home-17.jpg",
    "photos": [
      "assets/home-17.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 11,
    "photoCredit": "OneKey® MLS · Signature Premier Properties",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 18,
    "uid": "mls-1051429",
    "packetNumber": 18,
    "address": "38 Waterford Drive",
    "town": "Wheatley Heights",
    "price": 899000,
    "beds": 5,
    "baths": 3.5,
    "sqft": 2636,
    "acres": 0.23,
    "taxes": 15893,
    "dom": 11,
    "station": "Wyandanch",
    "drive": "5–7 min",
    "rail": "60 min to Penn · sample rail trip",
    "railMinutes": 60,
    "kitchen": "Not described in the listing.",
    "fit": "Five bedrooms, 2,636 listed sq ft, central air and a two-car garage.",
    "tradeoff": "Kitchen not described; top of budget and cesspool.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "Charles Rutenberg Realty",
    "mls": "1051429",
    "url": "https://portal.onehome.com/en-US/share/5534748e45307",
    "image": "assets/home-18.jpg",
    "photos": [
      "assets/home-18.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 11,
    "photoCredit": "OneKey® MLS · Charles Rutenberg Realty",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 19,
    "uid": "mls-1023194",
    "packetNumber": 19,
    "address": "59 Bushwick Street",
    "town": "Melville",
    "price": 839000,
    "beds": 5,
    "baths": 3.5,
    "sqft": 2039,
    "acres": 0.18,
    "taxes": 13889,
    "dom": 82,
    "station": "Wyandanch",
    "drive": "14–18 min",
    "rail": "60 min to Penn · sample rail trip",
    "railMinutes": 60,
    "kitchen": "Eat-in kitchen with an island and lots of cabinet space, open to the dining and living rooms; not described as recently updated.",
    "fit": "Five bedrooms, island kitchen and a listed legal accessory studio.",
    "tradeoff": "Kitchen update not stated; oil heat, window A/C and no garage.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "Charles Rutenberg Realty",
    "mls": "1023194",
    "url": "https://portal.onehome.com/en-US/share/5534744w19885",
    "image": "assets/home-19.jpg",
    "photos": [
      "assets/home-19.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 12,
    "photoCredit": "OneKey® MLS · Charles Rutenberg Realty",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 20,
    "uid": "mls-1052550",
    "packetNumber": 20,
    "address": "128 Crooked Hill Road",
    "town": "Huntington",
    "price": 849995,
    "beds": 4,
    "baths": 4,
    "sqft": 2000,
    "acres": 0.5,
    "taxes": 11157,
    "dom": 9,
    "station": "Huntington",
    "drive": "4 min",
    "rail": "66 min to Penn · sample rail trip",
    "railMinutes": 66,
    "kitchen": "Designer kitchen: soft-close custom cabinetry, quartz counters, center island with microwave drawer, Bosch appliances, 48-inch Bertazzoni propane range.",
    "fit": "Renovated island kitchen, four full baths and a half-acre lot.",
    "tradeoff": "2,000 listed sq ft; breakdown by floor needs confirmation; no garage and cesspool.",
    "verification": "MLS lists 2,000 sq ft and describes a finished lower level; separate measurements by floor need confirmation.",
    "broker": "Deal House Realty",
    "mls": "1052550",
    "url": "https://portal.onehome.com/en-US/share/5534706D17014",
    "image": "assets/home-20.jpg",
    "photos": [
      "assets/home-20.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 12,
    "photoCredit": "OneKey® MLS · Deal House Realty",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  },
  {
    "id": 21,
    "uid": "mls-1030366",
    "packetNumber": 21,
    "address": "2553 Motor Parkway",
    "town": "Ronkonkoma",
    "price": 899999,
    "beds": 4,
    "baths": 3,
    "sqft": 2040,
    "acres": 0.28,
    "taxes": 11676,
    "dom": 59,
    "station": "Ronkonkoma",
    "drive": "5–9 min",
    "rail": "78 min to Penn · sample rail trip",
    "railMinutes": 78,
    "kitchen": "Chef's kitchen with a center island, quartz counters, gas range and stainless appliances; open plan with cathedral ceilings.",
    "fit": "Renovated island kitchen, first-floor primary suite and detached garage.",
    "tradeoff": "On Motor Parkway; 2,040 listed sq ft, propane heat and cesspool.",
    "verification": "Listing-reported details; source packet September 28, 2026. Availability and dimensions need confirmation.",
    "broker": "Coldwell Banker American Homes",
    "mls": "1030366",
    "url": "https://portal.onehome.com/en-US/share/5534760j13298",
    "image": "assets/home-21.jpg",
    "photos": [
      "assets/home-21.jpg"
    ],
    "isOriginal": false,
    "sourceAsOf": "2026-09-28",
    "sourcePage": 13,
    "photoCredit": "OneKey® MLS · Coldwell Banker American Homes",
    "status": "Source packet snapshot — not live",
    "commuteNote": "Drive and rail are separate source estimates. Not a continuous departure-time itinerary; parking, walking and boarding time are additional."
  }
];
